version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_dev

    volumes:
      - ./db-data/:/var/lib/postgres/data/

  phx:
    build: .
    depends_on:
      - database
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - .:/app
