version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_dev

    volumes:
      - ./be/db-data/:/var/lib/postgres/data/

  phx:
    build: ./be
    depends_on:
      - database
    environment:
      MIX_ENV: dev
    env_file:
      - ./be/.env
    ports:
      - 4000:4000
    volumes:
      - ./be:/app

  phx-fe:
    build: ./fe
    depends_on:
      - phx
    ports:
      - 4001:4001
    volumes:
      - ./fe:/app
